import assert from 'assert';
import {getActiveDaysArray} from "../processor.js";

describe('getActiveDays', function () {
    const tests = [
        {
            arg:{
                "id": 245839,
                "term": "202020",
                "termDesc": "SEGUNDO SEMESTRE 2020",
                "courseReferenceNumber": "39342",
                "partOfTerm": "1",
                "courseNumber": "1101",
                "subject": "ADMI",
                "subjectDescription": "ADMINISTRACION",
                "sequenceNumber": "1",
                "campusDescription": "BLENDED - CAMPUS PRINCIPAL",
                "scheduleTypeDescription": "TEORICA",
                "courseTitle": "FUNDAMENTOS DE ADMINISTRACION Y GERENCIA (PARA ADMINISTRADORES)",
                "creditHours": null,
                "maximumEnrollment": 90,
                "enrollment": 0,
                "seatsAvailable": 90,
                "waitCapacity": 0,
                "waitCount": 0,
                "waitAvailable": 0,
                "crossList": null,
                "crossListCapacity": null,
                "crossListCount": null,
                "crossListAvailable": null,
                "creditHourHigh": null,
                "creditHourLow": 3,
                "creditHourIndicator": null,
                "openSection": true,
                "linkIdentifier": null,
                "isSectionLinked": false,
                "subjectCourse": "ADMI1101",
                "faculty": [
                    {
                        "bannerId": "199817573",
                        "category": null,
                        "class": "net.hedtech.banner.student.faculty.FacultyResultDecorator",
                        "courseReferenceNumber": "39342",
                        "displayName": "DIAZ MATAJIRA, LUIS",
                        "emailAddress": "luidiaz@uniandes.edu.co",
                        "primaryIndicator": true,
                        "term": "202020"
                    },
                    {
                        "bannerId": "6380143",
                        "category": null,
                        "class": "net.hedtech.banner.student.faculty.FacultyResultDecorator",
                        "courseReferenceNumber": "39342",
                        "displayName": "OROZCO SILVA, LUIS",
                        "emailAddress": "leorozco@uniandes.edu.co",
                        "primaryIndicator": false,
                        "term": "202020"
                    }
                ],
                "meetingsFaculty": [
                    {
                        "category": "01",
                        "class": "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                        "courseReferenceNumber": "39342",
                        "faculty": [],
                        "meetingTime": {
                            "beginTime": "1000",
                            "building": "VIRT",
                            "buildingDescription": "VIRTUAL",
                            "campus": "V",
                            "campusDescription": "VIRTUAL",
                            "category": "01",
                            "class": "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                            "courseReferenceNumber": "39342",
                            "creditHourSession": 0,
                            "endDate": "12/05/2020",
                            "endTime": "1115",
                            "friday": false,
                            "hoursWeek": 2.5,
                            "meetingScheduleType": "H",
                            "monday": true,
                            "room": "VIRT",
                            "saturday": false,
                            "startDate": "08/10/2020",
                            "sunday": false,
                            "term": "202020",
                            "thursday": false,
                            "tuesday": false,
                            "wednesday": true
                        },
                        "term": "202020"
                    },
                    {
                        "category": "01",
                        "class": "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                        "courseReferenceNumber": "39342",
                        "faculty": [],
                        "meetingTime": {
                            "beginTime": "1000",
                            "building": "C",
                            "buildingDescription": "Bloque C",
                            "campus": "P",
                            "campusDescription": "BLENDED - CAMPUS PRINCIPAL",
                            "category": "01",
                            "class": "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                            "courseReferenceNumber": "39342",
                            "creditHourSession": 0,
                            "endDate": "10/02/2020",
                            "endTime": "1115",
                            "friday": true,
                            "hoursWeek": 1.25,
                            "meetingScheduleType": "H",
                            "monday": false,
                            "room": "C_308",
                            "saturday": false,
                            "startDate": "08/14/2020",
                            "sunday": false,
                            "term": "202020",
                            "thursday": false,
                            "tuesday": false,
                            "wednesday": false
                        },
                        "term": "202020"
                    },
                    {
                        "category": "01",
                        "class": "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                        "courseReferenceNumber": "39342",
                        "faculty": [],
                        "meetingTime": {
                            "beginTime": "1000",
                            "building": "C",
                            "buildingDescription": "Bloque C",
                            "campus": "P",
                            "campusDescription": "BLENDED - CAMPUS PRINCIPAL",
                            "category": "01",
                            "class": "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                            "courseReferenceNumber": "39342",
                            "creditHourSession": 0,
                            "endDate": "11/27/2020",
                            "endTime": "1115",
                            "friday": true,
                            "hoursWeek": 1.25,
                            "meetingScheduleType": "H",
                            "monday": false,
                            "room": "C_308",
                            "saturday": false,
                            "startDate": "10/16/2020",
                            "sunday": false,
                            "term": "202020",
                            "thursday": false,
                            "tuesday": false,
                            "wednesday": false
                        },
                        "term": "202020"
                    }
                ],
                "reservedSeatSummary": null
            }.meetingsFaculty,
            expected: {
                monday:true,
                tuesday:false,
                wednesday:true,
                thursday:false,
                friday:true,
                saturday:false,
                sunday:false
            }
        },{
            arg:{
                "id": 247018,
                "term": "202020",
                "termDesc": "SEGUNDO SEMESTRE 2020",
                "courseReferenceNumber": "42986",
                "partOfTerm": "1",
                "courseNumber": "1101",
                "subject": "ADMI",
                "subjectDescription": "ADMINISTRACION",
                "sequenceNumber": "2",
                "campusDescription": "BLENDED - CAMPUS PRINCIPAL",
                "scheduleTypeDescription": "TEORICA",
                "courseTitle": "FUNDAMENTOS DE ADMINISTRACION Y GERENCIA (PARA ADMINISTRADORES)",
                "creditHours": null,
                "maximumEnrollment": 90,
                "enrollment": 0,
                "seatsAvailable": 90,
                "waitCapacity": 0,
                "waitCount": 0,
                "waitAvailable": 0,
                "crossList": null,
                "crossListCapacity": null,
                "crossListCount": null,
                "crossListAvailable": null,
                "creditHourHigh": null,
                "creditHourLow": 3,
                "creditHourIndicator": null,
                "openSection": true,
                "linkIdentifier": null,
                "isSectionLinked": false,
                "subjectCourse": "ADMI1101",
                "faculty": [
                    {
                        "bannerId": "199817573",
                        "category": null,
                        "class": "net.hedtech.banner.student.faculty.FacultyResultDecorator",
                        "courseReferenceNumber": "42986",
                        "displayName": "DIAZ MATAJIRA, LUIS",
                        "emailAddress": "luidiaz@uniandes.edu.co",
                        "primaryIndicator": true,
                        "term": "202020"
                    },
                    {
                        "bannerId": "6380143",
                        "category": null,
                        "class": "net.hedtech.banner.student.faculty.FacultyResultDecorator",
                        "courseReferenceNumber": "42986",
                        "displayName": "OROZCO SILVA, LUIS",
                        "emailAddress": "leorozco@uniandes.edu.co",
                        "primaryIndicator": false,
                        "term": "202020"
                    }
                ],
                "meetingsFaculty": [
                    {
                        "category": "01",
                        "class": "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                        "courseReferenceNumber": "42986",
                        "faculty": [],
                        "meetingTime": {
                            "beginTime": "1300",
                            "building": "VIRT",
                            "buildingDescription": "VIRTUAL",
                            "campus": "V",
                            "campusDescription": "VIRTUAL",
                            "category": "01",
                            "class": "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                            "courseReferenceNumber": "42986",
                            "creditHourSession": 3,
                            "endDate": "12/05/2020",
                            "endTime": "1415",
                            "friday": false,
                            "hoursWeek": 2.5,
                            "meetingScheduleType": "H",
                            "monday": true,
                            "room": "VIRT",
                            "saturday": false,
                            "startDate": "08/10/2020",
                            "sunday": false,
                            "term": "202020",
                            "thursday": false,
                            "tuesday": false,
                            "wednesday": true
                        },
                        "term": "202020"
                    },
                    {
                        "category": "01",
                        "class": "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                        "courseReferenceNumber": "42986",
                        "faculty": [],
                        "meetingTime": {
                            "beginTime": "1300",
                            "building": "SD",
                            "buildingDescription": "Edif. J.M.Santodomingo (SD)",
                            "campus": "P",
                            "campusDescription": "BLENDED - CAMPUS PRINCIPAL",
                            "category": "01",
                            "class": "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                            "courseReferenceNumber": "42986",
                            "creditHourSession": 0,
                            "endDate": "11/27/2020",
                            "endTime": "1415",
                            "friday": true,
                            "hoursWeek": 1.25,
                            "meetingScheduleType": "H",
                            "monday": false,
                            "room": "SD_804",
                            "saturday": false,
                            "startDate": "10/16/2020",
                            "sunday": false,
                            "term": "202020",
                            "thursday": false,
                            "tuesday": false,
                            "wednesday": false
                        },
                        "term": "202020"
                    },
                    {
                        "category": "01",
                        "class": "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                        "courseReferenceNumber": "42986",
                        "faculty": [],
                        "meetingTime": {
                            "beginTime": "1300",
                            "building": "SD",
                            "buildingDescription": "Edif. J.M.Santodomingo (SD)",
                            "campus": "P",
                            "campusDescription": "BLENDED - CAMPUS PRINCIPAL",
                            "category": "01",
                            "class": "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                            "courseReferenceNumber": "42986",
                            "creditHourSession": 0,
                            "endDate": "10/02/2020",
                            "endTime": "1415",
                            "friday": true,
                            "hoursWeek": 1.25,
                            "meetingScheduleType": "H",
                            "monday": false,
                            "room": "SD_804",
                            "saturday": false,
                            "startDate": "08/14/2020",
                            "sunday": false,
                            "term": "202020",
                            "thursday": false,
                            "tuesday": false,
                            "wednesday": false
                        },
                        "term": "202020"
                    }
                ],
                "reservedSeatSummary": null
            }.meetingsFaculty,
            expected: {
                monday:true,
                tuesday:false,
                wednesday:true,
                thursday:false,
                friday:true,
                saturday:false,
                sunday:false
            }
        },{
            arg:{
                "id": 250974,
                "term": "202020",
                "termDesc": "SEGUNDO SEMESTRE 2020",
                "courseReferenceNumber": "45716",
                "partOfTerm": "8B",
                "courseNumber": "2360",
                "subject": "ARQU",
                "subjectDescription": "ARQUITECTURA",
                "sequenceNumber": "6",
                "campusDescription": "BLENDED - CAMPUS PRINCIPAL",
                "scheduleTypeDescription": "TALLER TMS",
                "courseTitle": "UNC PROYECTO DEL TODO A LA ARTICULACI&Oacute;N ARM&Oacute;NICA DE LAS PARTES (Ciclo 2 de 8 semanas)",
                "creditHours": null,
                "maximumEnrollment": 10,
                "enrollment": 0,
                "seatsAvailable": 10,
                "waitCapacity": 0,
                "waitCount": 0,
                "waitAvailable": 0,
                "crossList": null,
                "crossListCapacity": null,
                "crossListCount": null,
                "crossListAvailable": null,
                "creditHourHigh": null,
                "creditHourLow": 3,
                "creditHourIndicator": null,
                "openSection": true,
                "linkIdentifier": null,
                "isSectionLinked": false,
                "subjectCourse": "ARQU2360",
                "faculty": [],
                "meetingsFaculty": [
                    {
                        "category": "01",
                        "class": "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                        "courseReferenceNumber": "45716",
                        "faculty": [],
                        "meetingTime": {
                            "beginTime": "1600",
                            "building": "C",
                            "buildingDescription": "Bloque C",
                            "campus": "P",
                            "campusDescription": "BLENDED - CAMPUS PRINCIPAL",
                            "category": "01",
                            "class": "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                            "courseReferenceNumber": "45716",
                            "creditHourSession": 0.0,
                            "endDate": "12/05/2020",
                            "endTime": "1845",
                            "friday": true,
                            "hoursWeek": 5.5,
                            "meetingScheduleType": "TB",
                            "monday": false,
                            "room": "C_303",
                            "saturday": false,
                            "startDate": "11/30/2020",
                            "sunday": false,
                            "term": "202020",
                            "thursday": false,
                            "tuesday": true,
                            "wednesday": false
                        },
                        "term": "202020"
                    },
                    {
                        "category": "01",
                        "class": "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                        "courseReferenceNumber": "45716",
                        "faculty": [],
                        "meetingTime": {
                            "beginTime": "1600",
                            "building": "VIRT",
                            "buildingDescription": "VIRTUAL",
                            "campus": "V",
                            "campusDescription": "VIRTUAL",
                            "category": "01",
                            "class": "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                            "courseReferenceNumber": "45716",
                            "creditHourSession": 3.0,
                            "endDate": "10/25/2020",
                            "endTime": "1845",
                            "friday": true,
                            "hoursWeek": 5.5,
                            "meetingScheduleType": "TB",
                            "monday": false,
                            "room": "VIRT",
                            "saturday": false,
                            "startDate": "10/13/2020",
                            "sunday": false,
                            "term": "202020",
                            "thursday": false,
                            "tuesday": true,
                            "wednesday": false
                        },
                        "term": "202020"
                    },
                    {
                        "category": "01",
                        "class": "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                        "courseReferenceNumber": "45716",
                        "faculty": [],
                        "meetingTime": {
                            "beginTime": "1600",
                            "building": "C",
                            "buildingDescription": "Bloque C",
                            "campus": "P",
                            "campusDescription": "BLENDED - CAMPUS PRINCIPAL",
                            "category": "01",
                            "class": "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                            "courseReferenceNumber": "45716",
                            "creditHourSession": 0.0,
                            "endDate": "11/01/2020",
                            "endTime": "1845",
                            "friday": true,
                            "hoursWeek": 5.5,
                            "meetingScheduleType": "TB",
                            "monday": false,
                            "room": "C_303",
                            "saturday": false,
                            "startDate": "10/26/2020",
                            "sunday": false,
                            "term": "202020",
                            "thursday": false,
                            "tuesday": true,
                            "wednesday": false
                        },
                        "term": "202020"
                    },
                    {
                        "category": "01",
                        "class": "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                        "courseReferenceNumber": "45716",
                        "faculty": [],
                        "meetingTime": {
                            "beginTime": "1600",
                            "building": "VIRT",
                            "buildingDescription": "VIRTUAL",
                            "campus": "V",
                            "campusDescription": "VIRTUAL",
                            "category": "01",
                            "class": "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                            "courseReferenceNumber": "45716",
                            "creditHourSession": 0.0,
                            "endDate": "11/29/2020",
                            "endTime": "1845",
                            "friday": true,
                            "hoursWeek": 5.5,
                            "meetingScheduleType": "TB",
                            "monday": false,
                            "room": "VIRT",
                            "saturday": false,
                            "startDate": "11/02/2020",
                            "sunday": false,
                            "term": "202020",
                            "thursday": false,
                            "tuesday": true,
                            "wednesday": false
                        },
                        "term": "202020"
                    }
                ],
                "reservedSeatSummary": null
            }.meetingsFaculty,
            expected: {
                monday:false,
                tuesday:true,
                wednesday:false,
                thursday:false,
                friday:true,
                saturday:false,
                sunday:false
            }
        },{
            arg:{
                "id": 244658,
                "term": "202020",
                "termDesc": "SEGUNDO SEMESTRE 2020",
                "courseReferenceNumber": "30622",
                "partOfTerm": "1",
                "courseNumber": "1118",
                "subject": "ARTE",
                "subjectDescription": "ARTE",
                "sequenceNumber": "2",
                "campusDescription": "BLENDED - CAMPUS PRINCIPAL",
                "scheduleTypeDescription": "TALLER TMS",
                "courseTitle": "FOTO B&Aacute;SICA 2 :DIGITAL",
                "creditHours": null,
                "maximumEnrollment": 15,
                "enrollment": 0,
                "seatsAvailable": 15,
                "waitCapacity": 0,
                "waitCount": 0,
                "waitAvailable": 0,
                "crossList": null,
                "crossListCapacity": null,
                "crossListCount": null,
                "crossListAvailable": null,
                "creditHourHigh": null,
                "creditHourLow": 3,
                "creditHourIndicator": null,
                "openSection": true,
                "linkIdentifier": null,
                "isSectionLinked": false,
                "subjectCourse": "ARTE1118",
                "faculty": [
                    {
                        "bannerId": "80082780",
                        "category": null,
                        "class": "net.hedtech.banner.student.faculty.FacultyResultDecorator",
                        "courseReferenceNumber": "30622",
                        "displayName": "FORERO RAMIREZ, SANTIAGO",
                        "emailAddress": "s.foreror@uniandes.edu.co",
                        "primaryIndicator": true,
                        "term": "202020"
                    }
                ],
                "meetingsFaculty": [
                    {
                        "category": "01",
                        "class": "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                        "courseReferenceNumber": "30622",
                        "faculty": [],
                        "meetingTime": {
                            "beginTime": "1730",
                            "building": "VIRT",
                            "buildingDescription": "VIRTUAL",
                            "campus": "V",
                            "campusDescription": "VIRTUAL",
                            "category": "01",
                            "class": "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                            "courseReferenceNumber": "30622",
                            "creditHourSession": 3.0,
                            "endDate": "12/05/2020",
                            "endTime": "2015",
                            "friday": false,
                            "hoursWeek": 2.75,
                            "meetingScheduleType": "TB",
                            "monday": false,
                            "room": "VIRT",
                            "saturday": false,
                            "startDate": "08/10/2020",
                            "sunday": false,
                            "term": "202020",
                            "thursday": false,
                            "tuesday": true,
                            "wednesday": false
                        },
                        "term": "202020"
                    },
                    {
                        "category": "01",
                        "class": "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                        "courseReferenceNumber": "30622",
                        "faculty": [],
                        "meetingTime": {
                            "beginTime": "1730",
                            "building": "TX",
                            "buildingDescription": "Bloque TX",
                            "campus": "P",
                            "campusDescription": "BLENDED - CAMPUS PRINCIPAL",
                            "category": "01",
                            "class": "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                            "courseReferenceNumber": "30622",
                            "creditHourSession": 0.0,
                            "endDate": "12/05/2020",
                            "endTime": "2015",
                            "friday": false,
                            "hoursWeek": 2.75,
                            "meetingScheduleType": "TB",
                            "monday": false,
                            "room": "TX_503",
                            "saturday": false,
                            "startDate": "08/10/2020",
                            "sunday": false,
                            "term": "202020",
                            "thursday": true,
                            "tuesday": false,
                            "wednesday": false
                        },
                        "term": "202020"
                    }
                ],
                "reservedSeatSummary": null
            }.meetingsFaculty,
            expected: {
                monday:false,
                tuesday:true,
                wednesday:false,
                thursday:true,
                friday:false,
                saturday:false,
                sunday:false
            }
        }
    ]
    tests.forEach(function (test) {
        it('should return correct list of days', () => {
            assert.deepStrictEqual(getActiveDaysArray(test.arg), test.expected);
        });
    })

})

